docs: libraries-bom 13.3.0
googleapis/google-http-java-client pull request #1161
Opened 2020-10-26 21:12 UTC by suztomo

@elharo @chingor13 Can you review this?

2020-10-26 21:20 UTC, elharo requested changes
13.3.0

2020-10-26 21:21 UTC, elharo commented
java.lang.AssertionError: expected:<1> but was:<2>
	at com.google.api.client.http.HttpRequestTracingTest.executeExceptionCreatesSpan(HttpRequestTracingTest.java:123)

2020-10-26 22:10 UTC, suztomo commented
Good catch. Fixed. I'll check the tests results.

2020-10-26 22:31 UTC, chingor13 approved these changes

2020-10-27 13:59 UTC, elharo approved these changes

2020-10-27 14:42 UTC, merged